// Code generated by gunion. DO NOT EDIT.

package collision

type _myUnionVariant int

const (
	_myUnionVariant__Invalid _myUnionVariant = 0
	_myUnionVariant__variant _myUnionVariant = 1
	_myUnionVariant__inner   _myUnionVariant = 2
	_myUnionVariant_Invalid  _myUnionVariant = 3
	_myUnionVariant_c        _myUnionVariant = 4
)

type MyUnionUnion struct {
	__variant _myUnionVariant
	__inner   myUnion
}

func (u *MyUnionUnion) Is__Invalid() bool {
	return u.__variant == _myUnionVariant__Invalid
}

func NewMyUnionUnion__Invalid() MyUnionUnion {
	return MyUnionUnion{__variant: _myUnionVariant__Invalid}
}

func (u *MyUnionUnion) Is__variant() bool {
	return u.__variant == _myUnionVariant__variant
}

func (u *MyUnionUnion) Unwrap__variant() int {
	if u.__variant != _myUnionVariant__variant {
		panic("called Unwrap__variant on wrong variant")
	}
	return u.__inner._variant
}

func (u *MyUnionUnion) Get__variant() (int, bool) {
	if u.__variant == _myUnionVariant__variant {
		return u.__inner._variant, true
	}
	var zero int
	return zero, false
}

func NewMyUnionUnion__variant(val int) MyUnionUnion {
	return MyUnionUnion{
		__inner:   myUnion{_variant: val},
		__variant: _myUnionVariant__variant,
	}
}

func (u *MyUnionUnion) Is__inner() bool {
	return u.__variant == _myUnionVariant__inner
}

func (u *MyUnionUnion) Unwrap__inner() string {
	if u.__variant != _myUnionVariant__inner {
		panic("called Unwrap__inner on wrong variant")
	}
	return u.__inner._inner
}

func (u *MyUnionUnion) Get__inner() (string, bool) {
	if u.__variant == _myUnionVariant__inner {
		return u.__inner._inner, true
	}
	var zero string
	return zero, false
}

func NewMyUnionUnion__inner(val string) MyUnionUnion {
	return MyUnionUnion{
		__inner:   myUnion{_inner: val},
		__variant: _myUnionVariant__inner,
	}
}

func (u *MyUnionUnion) Is_Invalid() bool {
	return u.__variant == _myUnionVariant_Invalid
}

func (u *MyUnionUnion) Unwrap_Invalid() bool {
	if u.__variant != _myUnionVariant_Invalid {
		panic("called Unwrap_Invalid on wrong variant")
	}
	return u.__inner.Invalid
}

func (u *MyUnionUnion) Get_Invalid() (bool, bool) {
	if u.__variant == _myUnionVariant_Invalid {
		return u.__inner.Invalid, true
	}
	var zero bool
	return zero, false
}

func NewMyUnionUnion_Invalid(val bool) MyUnionUnion {
	return MyUnionUnion{
		__inner:   myUnion{Invalid: val},
		__variant: _myUnionVariant_Invalid,
	}
}

func (u *MyUnionUnion) Is_c() bool {
	return u.__variant == _myUnionVariant_c
}

func (u *MyUnionUnion) Unwrap_c() float64 {
	if u.__variant != _myUnionVariant_c {
		panic("called Unwrap_c on wrong variant")
	}
	return u.__inner.c
}

func (u *MyUnionUnion) Get_c() (float64, bool) {
	if u.__variant == _myUnionVariant_c {
		return u.__inner.c, true
	}
	var zero float64
	return zero, false
}

func NewMyUnionUnion_c(val float64) MyUnionUnion {
	return MyUnionUnion{
		__inner:   myUnion{c: val},
		__variant: _myUnionVariant_c,
	}
}

func Match_MyUnionUnion[_R any](u *MyUnionUnion, on__variant func(int) _R, on__inner func(string) _R, on_Invalid func(bool) _R, on_c func(float64) _R, on__Invalid func() _R) _R {
	switch u.__variant {
	case _myUnionVariant__variant:
		return on__variant(u.__inner._variant)
	case _myUnionVariant__inner:
		return on__inner(u.__inner._inner)
	case _myUnionVariant_Invalid:
		return on_Invalid(u.__inner.Invalid)
	case _myUnionVariant_c:
		return on_c(u.__inner.c)
	case _myUnionVariant__Invalid:
		return on__Invalid()
	default:
		panic("unreachable")
	}
}
