// Code generated by gunion via `/home/sid/.cache/go-build/95/95ef01e92306c8cd1466caa907c6db0435c16918242227ae7320a0598f475c9b-d/gunion --type shape --no-default`. DO NOT EDIT.

package example

type _shapeVariant int

const (
	_shapeVariant_Invalid   _shapeVariant = 0
	_shapeVariant_circle    _shapeVariant = 1
	_shapeVariant_rectangle _shapeVariant = 2
	_shapeVariant_triangle  _shapeVariant = 3
)

func (v _shapeVariant) String() string {
	switch v {
	case _shapeVariant_Invalid:
		return "Invalid"
	case _shapeVariant_circle:
		return "circle"
	case _shapeVariant_rectangle:
		return "rectangle"
	case _shapeVariant_triangle:
		return "triangle"
	default:
		return "unknown"
	}
}

type ShapeUnion struct {
	_variant _shapeVariant
	_inner   shape
}

func (u *ShapeUnion) Is_Invalid() bool {
	return u._variant == _shapeVariant_Invalid
}

func NewShapeUnion_Invalid() ShapeUnion {
	return ShapeUnion{_variant: _shapeVariant_Invalid}
}

func (u *ShapeUnion) Is_circle() bool {
	return u._variant == _shapeVariant_circle
}

func (u *ShapeUnion) Unwrap_circle() float64 {
	if u._variant != _shapeVariant_circle {
		panic("called Unwrap_circle on wrong variant")
	}
	return u._inner.circle
}

func (u *ShapeUnion) Get_circle() (float64, bool) {
	if u._variant == _shapeVariant_circle {
		return u._inner.circle, true
	}
	var zero float64
	return zero, false
}

func NewShapeUnion_circle(val float64) ShapeUnion {
	return ShapeUnion{
		_inner:   shape{circle: val},
		_variant: _shapeVariant_circle,
	}
}

func (u *ShapeUnion) Is_rectangle() bool {
	return u._variant == _shapeVariant_rectangle
}

func (u *ShapeUnion) Unwrap_rectangle() [2]float64 {
	if u._variant != _shapeVariant_rectangle {
		panic("called Unwrap_rectangle on wrong variant")
	}
	return u._inner.rectangle
}

func (u *ShapeUnion) Get_rectangle() ([2]float64, bool) {
	if u._variant == _shapeVariant_rectangle {
		return u._inner.rectangle, true
	}
	var zero [2]float64
	return zero, false
}

func NewShapeUnion_rectangle(val [2]float64) ShapeUnion {
	return ShapeUnion{
		_inner:   shape{rectangle: val},
		_variant: _shapeVariant_rectangle,
	}
}

func (u *ShapeUnion) Is_triangle() bool {
	return u._variant == _shapeVariant_triangle
}

func (u *ShapeUnion) Unwrap_triangle() [3]float64 {
	if u._variant != _shapeVariant_triangle {
		panic("called Unwrap_triangle on wrong variant")
	}
	return u._inner.triangle
}

func (u *ShapeUnion) Get_triangle() ([3]float64, bool) {
	if u._variant == _shapeVariant_triangle {
		return u._inner.triangle, true
	}
	var zero [3]float64
	return zero, false
}

func NewShapeUnion_triangle(val [3]float64) ShapeUnion {
	return ShapeUnion{
		_inner:   shape{triangle: val},
		_variant: _shapeVariant_triangle,
	}
}

func Match_ShapeUnion[_R any](u *ShapeUnion, on_circle func(float64) _R, on_rectangle func([2]float64) _R, on_triangle func([3]float64) _R, on_Invalid func() _R) _R {
	switch u._variant {
	case _shapeVariant_circle:
		return on_circle(u._inner.circle)
	case _shapeVariant_rectangle:
		return on_rectangle(u._inner.rectangle)
	case _shapeVariant_triangle:
		return on_triangle(u._inner.triangle)
	case _shapeVariant_Invalid:
		return on_Invalid()
	default:
		panic("unreachable")
	}
}
