version: 2

project_name: gunion

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: gunion
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - images:
      - "sidkurella/gunion"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "latest"
