// Code generated by gunion. DO NOT EDIT.

package imported

import inner "github.com/sidkurella/gunion/internal/testdata/imported/inner"

type _myUnionVariant int

const (
	_myUnionVariant__invalid _myUnionVariant = 0
	_myUnionVariant_a        _myUnionVariant = 1
	_myUnionVariant_b        _myUnionVariant = 2
)

type MyUnionUnion struct {
	variant _myUnionVariant
	inner   myUnion
}

func (u *MyUnionUnion) Is_Invalid() bool {
	return u.variant == _myUnionVariant__invalid
}

func NewMyUnionUnion_Invalid() MyUnionUnion {
	return MyUnionUnion{variant: _myUnionVariant__invalid}
}

func (u *MyUnionUnion) Is_a() bool {
	return u.variant == _myUnionVariant_a
}

func (u *MyUnionUnion) Unwrap_a() int {
	if u.variant != _myUnionVariant_a {
		panic("called Unwrap_a on wrong variant")
	}
	return u.inner.a
}

func (u *MyUnionUnion) Get_a() (int, bool) {
	if u.variant == _myUnionVariant_a {
		return u.inner.a, true
	}
	var zero int
	return zero, false
}

func NewMyUnionUnion_a(val int) MyUnionUnion {
	return MyUnionUnion{
		inner:   myUnion{a: val},
		variant: _myUnionVariant_a,
	}
}

func (u *MyUnionUnion) Is_b() bool {
	return u.variant == _myUnionVariant_b
}

func (u *MyUnionUnion) Unwrap_b() inner.MyValue {
	if u.variant != _myUnionVariant_b {
		panic("called Unwrap_b on wrong variant")
	}
	return u.inner.b
}

func (u *MyUnionUnion) Get_b() (inner.MyValue, bool) {
	if u.variant == _myUnionVariant_b {
		return u.inner.b, true
	}
	var zero inner.MyValue
	return zero, false
}

func NewMyUnionUnion_b(val inner.MyValue) MyUnionUnion {
	return MyUnionUnion{
		inner:   myUnion{b: val},
		variant: _myUnionVariant_b,
	}
}

func Match_MyUnionUnion[_R any](u *MyUnionUnion, on_a func(int) _R, on_b func(inner.MyValue) _R, on_Invalid func() _R) _R {
	switch u.variant {
	case _myUnionVariant_a:
		return on_a(u.inner.a)
	case _myUnionVariant_b:
		return on_b(u.inner.b)
	case _myUnionVariant__invalid:
		return on_Invalid()
	default:
		panic("unreachable")
	}
}
