// Code generated by gunion. DO NOT EDIT.

package basic

type _myUnionVariant int

const (
	_myUnionVariant_a _myUnionVariant = 0
	_myUnionVariant_b _myUnionVariant = 1
)

func (v _myUnionVariant) String() string {
	switch v {
	case _myUnionVariant_a:
		return "a"
	case _myUnionVariant_b:
		return "b"
	default:
		return "unknown"
	}
}

type MyUnionUnion struct {
	_variant _myUnionVariant
	_inner   myUnion
}

func (u *MyUnionUnion) Is_a() bool {
	return u._variant == _myUnionVariant_a
}

func (u *MyUnionUnion) Unwrap_a() int {
	if u._variant != _myUnionVariant_a {
		panic("called Unwrap_a on wrong variant")
	}
	return u._inner.a
}

func (u *MyUnionUnion) Get_a() (int, bool) {
	if u._variant == _myUnionVariant_a {
		return u._inner.a, true
	}
	var zero int
	return zero, false
}

func NewMyUnionUnion_a(val int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{a: val},
		_variant: _myUnionVariant_a,
	}
}

func (u *MyUnionUnion) Is_b() bool {
	return u._variant == _myUnionVariant_b
}

func (u *MyUnionUnion) Unwrap_b() string {
	if u._variant != _myUnionVariant_b {
		panic("called Unwrap_b on wrong variant")
	}
	return u._inner.b
}

func (u *MyUnionUnion) Get_b() (string, bool) {
	if u._variant == _myUnionVariant_b {
		return u._inner.b, true
	}
	var zero string
	return zero, false
}

func NewMyUnionUnion_b(val string) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{b: val},
		_variant: _myUnionVariant_b,
	}
}

func Match_MyUnionUnion[_R any](u *MyUnionUnion, on_a func(int) _R, on_b func(string) _R) _R {
	switch u._variant {
	case _myUnionVariant_a:
		return on_a(u._inner.a)
	case _myUnionVariant_b:
		return on_b(u._inner.b)
	default:
		panic("unreachable")
	}
}
