// Code generated by gunion. DO NOT EDIT.

package basic

type _myUnionVariant int

const (
	_myUnionVariant_Invalid _myUnionVariant = 0
	_myUnionVariant_a       _myUnionVariant = 1
	_myUnionVariant_b       _myUnionVariant = 2
)

type MyUnionUnion struct {
	_variant _myUnionVariant
	_inner   myUnion
}
