// Code generated by gunion. DO NOT EDIT.

package torture

import (
	"context"
	"io"
	"time"
)

type _myUnionVariant int

const (
	_myUnionVariant_Invalid _myUnionVariant = 0
	_myUnionVariant_a       _myUnionVariant = 1
	_myUnionVariant_b       _myUnionVariant = 2
	_myUnionVariant_c       _myUnionVariant = 3
	_myUnionVariant_d       _myUnionVariant = 4
	_myUnionVariant_e       _myUnionVariant = 5
	_myUnionVariant_f       _myUnionVariant = 6
	_myUnionVariant_g       _myUnionVariant = 7
	_myUnionVariant_h       _myUnionVariant = 8
	_myUnionVariant_i       _myUnionVariant = 9
	_myUnionVariant_j       _myUnionVariant = 10
	_myUnionVariant_k       _myUnionVariant = 11
	_myUnionVariant_l       _myUnionVariant = 12
	_myUnionVariant_m       _myUnionVariant = 13
	_myUnionVariant_n       _myUnionVariant = 14
	_myUnionVariant_o       _myUnionVariant = 15
	_myUnionVariant_p       _myUnionVariant = 16
	_myUnionVariant_q       _myUnionVariant = 17
	_myUnionVariant_r       _myUnionVariant = 18
	_myUnionVariant_s       _myUnionVariant = 19
	_myUnionVariant_t       _myUnionVariant = 20
	_myUnionVariant_u       _myUnionVariant = 21
	_myUnionVariant_v       _myUnionVariant = 22
	_myUnionVariant_w       _myUnionVariant = 23
	_myUnionVariant_x       _myUnionVariant = 24
	_myUnionVariant_y       _myUnionVariant = 25
	_myUnionVariant_z       _myUnionVariant = 26
	_myUnionVariant_aa      _myUnionVariant = 27
	_myUnionVariant_bb      _myUnionVariant = 28
	_myUnionVariant_cc      _myUnionVariant = 29
	_myUnionVariant_dd      _myUnionVariant = 30
	_myUnionVariant_ee      _myUnionVariant = 31
	_myUnionVariant_ff      _myUnionVariant = 32
	_myUnionVariant_gg      _myUnionVariant = 33
	_myUnionVariant_hh      _myUnionVariant = 34
	_myUnionVariant_ii      _myUnionVariant = 35
	_myUnionVariant_jj      _myUnionVariant = 36
	_myUnionVariant_kk      _myUnionVariant = 37
	_myUnionVariant_ll      _myUnionVariant = 38
	_myUnionVariant_mm      _myUnionVariant = 39
	_myUnionVariant_nn      _myUnionVariant = 40
	_myUnionVariant_oo      _myUnionVariant = 41
	_myUnionVariant_pp      _myUnionVariant = 42
)

func (v _myUnionVariant) String() string {
	switch v {
	case _myUnionVariant_Invalid:
		return "Invalid"
	case _myUnionVariant_a:
		return "a"
	case _myUnionVariant_b:
		return "b"
	case _myUnionVariant_c:
		return "c"
	case _myUnionVariant_d:
		return "d"
	case _myUnionVariant_e:
		return "e"
	case _myUnionVariant_f:
		return "f"
	case _myUnionVariant_g:
		return "g"
	case _myUnionVariant_h:
		return "h"
	case _myUnionVariant_i:
		return "i"
	case _myUnionVariant_j:
		return "j"
	case _myUnionVariant_k:
		return "k"
	case _myUnionVariant_l:
		return "l"
	case _myUnionVariant_m:
		return "m"
	case _myUnionVariant_n:
		return "n"
	case _myUnionVariant_o:
		return "o"
	case _myUnionVariant_p:
		return "p"
	case _myUnionVariant_q:
		return "q"
	case _myUnionVariant_r:
		return "r"
	case _myUnionVariant_s:
		return "s"
	case _myUnionVariant_t:
		return "t"
	case _myUnionVariant_u:
		return "u"
	case _myUnionVariant_v:
		return "v"
	case _myUnionVariant_w:
		return "w"
	case _myUnionVariant_x:
		return "x"
	case _myUnionVariant_y:
		return "y"
	case _myUnionVariant_z:
		return "z"
	case _myUnionVariant_aa:
		return "aa"
	case _myUnionVariant_bb:
		return "bb"
	case _myUnionVariant_cc:
		return "cc"
	case _myUnionVariant_dd:
		return "dd"
	case _myUnionVariant_ee:
		return "ee"
	case _myUnionVariant_ff:
		return "ff"
	case _myUnionVariant_gg:
		return "gg"
	case _myUnionVariant_hh:
		return "hh"
	case _myUnionVariant_ii:
		return "ii"
	case _myUnionVariant_jj:
		return "jj"
	case _myUnionVariant_kk:
		return "kk"
	case _myUnionVariant_ll:
		return "ll"
	case _myUnionVariant_mm:
		return "mm"
	case _myUnionVariant_nn:
		return "nn"
	case _myUnionVariant_oo:
		return "oo"
	case _myUnionVariant_pp:
		return "pp"
	default:
		return "unknown"
	}
}

type MyUnionUnion struct {
	_variant _myUnionVariant
	_inner   myUnion
}

func (u *MyUnionUnion) Is_Invalid() bool {
	return u._variant == _myUnionVariant_Invalid
}

func NewMyUnionUnion_Invalid() MyUnionUnion {
	return MyUnionUnion{_variant: _myUnionVariant_Invalid}
}

func (u *MyUnionUnion) Is_a() bool {
	return u._variant == _myUnionVariant_a
}

func (u *MyUnionUnion) Unwrap_a() int {
	if u._variant != _myUnionVariant_a {
		panic("called Unwrap_a on wrong variant")
	}
	return u._inner.a
}

func (u *MyUnionUnion) Get_a() (int, bool) {
	if u._variant == _myUnionVariant_a {
		return u._inner.a, true
	}
	var zero int
	return zero, false
}

func NewMyUnionUnion_a(val int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{a: val},
		_variant: _myUnionVariant_a,
	}
}

func (u *MyUnionUnion) Is_b() bool {
	return u._variant == _myUnionVariant_b
}

func (u *MyUnionUnion) Unwrap_b() string {
	if u._variant != _myUnionVariant_b {
		panic("called Unwrap_b on wrong variant")
	}
	return u._inner.b
}

func (u *MyUnionUnion) Get_b() (string, bool) {
	if u._variant == _myUnionVariant_b {
		return u._inner.b, true
	}
	var zero string
	return zero, false
}

func NewMyUnionUnion_b(val string) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{b: val},
		_variant: _myUnionVariant_b,
	}
}

func (u *MyUnionUnion) Is_c() bool {
	return u._variant == _myUnionVariant_c
}

func (u *MyUnionUnion) Unwrap_c() *float64 {
	if u._variant != _myUnionVariant_c {
		panic("called Unwrap_c on wrong variant")
	}
	return u._inner.c
}

func (u *MyUnionUnion) Get_c() (*float64, bool) {
	if u._variant == _myUnionVariant_c {
		return u._inner.c, true
	}
	var zero *float64
	return zero, false
}

func NewMyUnionUnion_c(val *float64) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{c: val},
		_variant: _myUnionVariant_c,
	}
}

func (u *MyUnionUnion) Is_d() bool {
	return u._variant == _myUnionVariant_d
}

func (u *MyUnionUnion) Unwrap_d() []*int {
	if u._variant != _myUnionVariant_d {
		panic("called Unwrap_d on wrong variant")
	}
	return u._inner.d
}

func (u *MyUnionUnion) Get_d() ([]*int, bool) {
	if u._variant == _myUnionVariant_d {
		return u._inner.d, true
	}
	var zero []*int
	return zero, false
}

func NewMyUnionUnion_d(val []*int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{d: val},
		_variant: _myUnionVariant_d,
	}
}

func (u *MyUnionUnion) Is_e() bool {
	return u._variant == _myUnionVariant_e
}

func (u *MyUnionUnion) Unwrap_e() [5]byte {
	if u._variant != _myUnionVariant_e {
		panic("called Unwrap_e on wrong variant")
	}
	return u._inner.e
}

func (u *MyUnionUnion) Get_e() ([5]byte, bool) {
	if u._variant == _myUnionVariant_e {
		return u._inner.e, true
	}
	var zero [5]byte
	return zero, false
}

func NewMyUnionUnion_e(val [5]byte) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{e: val},
		_variant: _myUnionVariant_e,
	}
}

func (u *MyUnionUnion) Is_f() bool {
	return u._variant == _myUnionVariant_f
}

func (u *MyUnionUnion) Unwrap_f() map[string][]int {
	if u._variant != _myUnionVariant_f {
		panic("called Unwrap_f on wrong variant")
	}
	return u._inner.f
}

func (u *MyUnionUnion) Get_f() (map[string][]int, bool) {
	if u._variant == _myUnionVariant_f {
		return u._inner.f, true
	}
	var zero map[string][]int
	return zero, false
}

func NewMyUnionUnion_f(val map[string][]int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{f: val},
		_variant: _myUnionVariant_f,
	}
}

func (u *MyUnionUnion) Is_g() bool {
	return u._variant == _myUnionVariant_g
}

func (u *MyUnionUnion) Unwrap_g() map[int]map[string]bool {
	if u._variant != _myUnionVariant_g {
		panic("called Unwrap_g on wrong variant")
	}
	return u._inner.g
}

func (u *MyUnionUnion) Get_g() (map[int]map[string]bool, bool) {
	if u._variant == _myUnionVariant_g {
		return u._inner.g, true
	}
	var zero map[int]map[string]bool
	return zero, false
}

func NewMyUnionUnion_g(val map[int]map[string]bool) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{g: val},
		_variant: _myUnionVariant_g,
	}
}

func (u *MyUnionUnion) Is_h() bool {
	return u._variant == _myUnionVariant_h
}

func (u *MyUnionUnion) Unwrap_h() chan int {
	if u._variant != _myUnionVariant_h {
		panic("called Unwrap_h on wrong variant")
	}
	return u._inner.h
}

func (u *MyUnionUnion) Get_h() (chan int, bool) {
	if u._variant == _myUnionVariant_h {
		return u._inner.h, true
	}
	var zero chan int
	return zero, false
}

func NewMyUnionUnion_h(val chan int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{h: val},
		_variant: _myUnionVariant_h,
	}
}

func (u *MyUnionUnion) Is_i() bool {
	return u._variant == _myUnionVariant_i
}

func (u *MyUnionUnion) Unwrap_i() <-chan string {
	if u._variant != _myUnionVariant_i {
		panic("called Unwrap_i on wrong variant")
	}
	return u._inner.i
}

func (u *MyUnionUnion) Get_i() (<-chan string, bool) {
	if u._variant == _myUnionVariant_i {
		return u._inner.i, true
	}
	var zero <-chan string
	return zero, false
}

func NewMyUnionUnion_i(val <-chan string) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{i: val},
		_variant: _myUnionVariant_i,
	}
}

func (u *MyUnionUnion) Is_j() bool {
	return u._variant == _myUnionVariant_j
}

func (u *MyUnionUnion) Unwrap_j() chan<- bool {
	if u._variant != _myUnionVariant_j {
		panic("called Unwrap_j on wrong variant")
	}
	return u._inner.j
}

func (u *MyUnionUnion) Get_j() (chan<- bool, bool) {
	if u._variant == _myUnionVariant_j {
		return u._inner.j, true
	}
	var zero chan<- bool
	return zero, false
}

func NewMyUnionUnion_j(val chan<- bool) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{j: val},
		_variant: _myUnionVariant_j,
	}
}

func (u *MyUnionUnion) Is_k() bool {
	return u._variant == _myUnionVariant_k
}

func (u *MyUnionUnion) Unwrap_k() func() {
	if u._variant != _myUnionVariant_k {
		panic("called Unwrap_k on wrong variant")
	}
	return u._inner.k
}

func (u *MyUnionUnion) Get_k() (func(), bool) {
	if u._variant == _myUnionVariant_k {
		return u._inner.k, true
	}
	var zero func()
	return zero, false
}

func NewMyUnionUnion_k(val func()) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{k: val},
		_variant: _myUnionVariant_k,
	}
}

func (u *MyUnionUnion) Is_l() bool {
	return u._variant == _myUnionVariant_l
}

func (u *MyUnionUnion) Unwrap_l() func(a int, b string) (int, error) {
	if u._variant != _myUnionVariant_l {
		panic("called Unwrap_l on wrong variant")
	}
	return u._inner.l
}

func (u *MyUnionUnion) Get_l() (func(a int, b string) (int, error), bool) {
	if u._variant == _myUnionVariant_l {
		return u._inner.l, true
	}
	var zero func(a int, b string) (int, error)
	return zero, false
}

func NewMyUnionUnion_l(val func(a int, b string) (int, error)) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{l: val},
		_variant: _myUnionVariant_l,
	}
}

func (u *MyUnionUnion) Is_m() bool {
	return u._variant == _myUnionVariant_m
}

func (u *MyUnionUnion) Unwrap_m() func(format string, args ...any) string {
	if u._variant != _myUnionVariant_m {
		panic("called Unwrap_m on wrong variant")
	}
	return u._inner.m
}

func (u *MyUnionUnion) Get_m() (func(format string, args ...any) string, bool) {
	if u._variant == _myUnionVariant_m {
		return u._inner.m, true
	}
	var zero func(format string, args ...any) string
	return zero, false
}

func NewMyUnionUnion_m(val func(format string, args ...any) string) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{m: val},
		_variant: _myUnionVariant_m,
	}
}

func (u *MyUnionUnion) Is_n() bool {
	return u._variant == _myUnionVariant_n
}

func (u *MyUnionUnion) Unwrap_n() func(x int, y int) (sum int, diff int) {
	if u._variant != _myUnionVariant_n {
		panic("called Unwrap_n on wrong variant")
	}
	return u._inner.n
}

func (u *MyUnionUnion) Get_n() (func(x int, y int) (sum int, diff int), bool) {
	if u._variant == _myUnionVariant_n {
		return u._inner.n, true
	}
	var zero func(x int, y int) (sum int, diff int)
	return zero, false
}

func NewMyUnionUnion_n(val func(x int, y int) (sum int, diff int)) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{n: val},
		_variant: _myUnionVariant_n,
	}
}

func (u *MyUnionUnion) Is_o() bool {
	return u._variant == _myUnionVariant_o
}

func (u *MyUnionUnion) Unwrap_o() func(multiplier int) func(int) int {
	if u._variant != _myUnionVariant_o {
		panic("called Unwrap_o on wrong variant")
	}
	return u._inner.o
}

func (u *MyUnionUnion) Get_o() (func(multiplier int) func(int) int, bool) {
	if u._variant == _myUnionVariant_o {
		return u._inner.o, true
	}
	var zero func(multiplier int) func(int) int
	return zero, false
}

func NewMyUnionUnion_o(val func(multiplier int) func(int) int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{o: val},
		_variant: _myUnionVariant_o,
	}
}

func (u *MyUnionUnion) Is_p() bool {
	return u._variant == _myUnionVariant_p
}

func (u *MyUnionUnion) Unwrap_p() func(callback func(int) bool) error {
	if u._variant != _myUnionVariant_p {
		panic("called Unwrap_p on wrong variant")
	}
	return u._inner.p
}

func (u *MyUnionUnion) Get_p() (func(callback func(int) bool) error, bool) {
	if u._variant == _myUnionVariant_p {
		return u._inner.p, true
	}
	var zero func(callback func(int) bool) error
	return zero, false
}

func NewMyUnionUnion_p(val func(callback func(int) bool) error) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{p: val},
		_variant: _myUnionVariant_p,
	}
}

func (u *MyUnionUnion) Is_q() bool {
	return u._variant == _myUnionVariant_q
}

func (u *MyUnionUnion) Unwrap_q() func(in <-chan int, out chan<- int) {
	if u._variant != _myUnionVariant_q {
		panic("called Unwrap_q on wrong variant")
	}
	return u._inner.q
}

func (u *MyUnionUnion) Get_q() (func(in <-chan int, out chan<- int), bool) {
	if u._variant == _myUnionVariant_q {
		return u._inner.q, true
	}
	var zero func(in <-chan int, out chan<- int)
	return zero, false
}

func NewMyUnionUnion_q(val func(in <-chan int, out chan<- int)) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{q: val},
		_variant: _myUnionVariant_q,
	}
}

func (u *MyUnionUnion) Is_r() bool {
	return u._variant == _myUnionVariant_r
}

func (u *MyUnionUnion) Unwrap_r() func(ctx context.Context) error {
	if u._variant != _myUnionVariant_r {
		panic("called Unwrap_r on wrong variant")
	}
	return u._inner.r
}

func (u *MyUnionUnion) Get_r() (func(ctx context.Context) error, bool) {
	if u._variant == _myUnionVariant_r {
		return u._inner.r, true
	}
	var zero func(ctx context.Context) error
	return zero, false
}

func NewMyUnionUnion_r(val func(ctx context.Context) error) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{r: val},
		_variant: _myUnionVariant_r,
	}
}

func (u *MyUnionUnion) Is_s() bool {
	return u._variant == _myUnionVariant_s
}

func (u *MyUnionUnion) Unwrap_s() func(w io.Writer, r io.Reader) (int64, error) {
	if u._variant != _myUnionVariant_s {
		panic("called Unwrap_s on wrong variant")
	}
	return u._inner.s
}

func (u *MyUnionUnion) Get_s() (func(w io.Writer, r io.Reader) (int64, error), bool) {
	if u._variant == _myUnionVariant_s {
		return u._inner.s, true
	}
	var zero func(w io.Writer, r io.Reader) (int64, error)
	return zero, false
}

func NewMyUnionUnion_s(val func(w io.Writer, r io.Reader) (int64, error)) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{s: val},
		_variant: _myUnionVariant_s,
	}
}

func (u *MyUnionUnion) Is_t() bool {
	return u._variant == _myUnionVariant_t
}

func (u *MyUnionUnion) Unwrap_t() *func(int) int {
	if u._variant != _myUnionVariant_t {
		panic("called Unwrap_t on wrong variant")
	}
	return u._inner.t
}

func (u *MyUnionUnion) Get_t() (*func(int) int, bool) {
	if u._variant == _myUnionVariant_t {
		return u._inner.t, true
	}
	var zero *func(int) int
	return zero, false
}

func NewMyUnionUnion_t(val *func(int) int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{t: val},
		_variant: _myUnionVariant_t,
	}
}

func (u *MyUnionUnion) Is_u() bool {
	return u._variant == _myUnionVariant_u
}

func (u *MyUnionUnion) Unwrap_u() []func() error {
	if u._variant != _myUnionVariant_u {
		panic("called Unwrap_u on wrong variant")
	}
	return u._inner.u
}

func (u *MyUnionUnion) Get_u() ([]func() error, bool) {
	if u._variant == _myUnionVariant_u {
		return u._inner.u, true
	}
	var zero []func() error
	return zero, false
}

func NewMyUnionUnion_u(val []func() error) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{u: val},
		_variant: _myUnionVariant_u,
	}
}

func (u *MyUnionUnion) Is_v() bool {
	return u._variant == _myUnionVariant_v
}

func (u *MyUnionUnion) Unwrap_v() map[string]func(int) int {
	if u._variant != _myUnionVariant_v {
		panic("called Unwrap_v on wrong variant")
	}
	return u._inner.v
}

func (u *MyUnionUnion) Get_v() (map[string]func(int) int, bool) {
	if u._variant == _myUnionVariant_v {
		return u._inner.v, true
	}
	var zero map[string]func(int) int
	return zero, false
}

func NewMyUnionUnion_v(val map[string]func(int) int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{v: val},
		_variant: _myUnionVariant_v,
	}
}

func (u *MyUnionUnion) Is_w() bool {
	return u._variant == _myUnionVariant_w
}

func (u *MyUnionUnion) Unwrap_w() ***int {
	if u._variant != _myUnionVariant_w {
		panic("called Unwrap_w on wrong variant")
	}
	return u._inner.w
}

func (u *MyUnionUnion) Get_w() (***int, bool) {
	if u._variant == _myUnionVariant_w {
		return u._inner.w, true
	}
	var zero ***int
	return zero, false
}

func NewMyUnionUnion_w(val ***int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{w: val},
		_variant: _myUnionVariant_w,
	}
}

func (u *MyUnionUnion) Is_x() bool {
	return u._variant == _myUnionVariant_x
}

func (u *MyUnionUnion) Unwrap_x() *[]*[3]int {
	if u._variant != _myUnionVariant_x {
		panic("called Unwrap_x on wrong variant")
	}
	return u._inner.x
}

func (u *MyUnionUnion) Get_x() (*[]*[3]int, bool) {
	if u._variant == _myUnionVariant_x {
		return u._inner.x, true
	}
	var zero *[]*[3]int
	return zero, false
}

func NewMyUnionUnion_x(val *[]*[3]int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{x: val},
		_variant: _myUnionVariant_x,
	}
}

func (u *MyUnionUnion) Is_y() bool {
	return u._variant == _myUnionVariant_y
}

func (u *MyUnionUnion) Unwrap_y() func(*int, **string) *bool {
	if u._variant != _myUnionVariant_y {
		panic("called Unwrap_y on wrong variant")
	}
	return u._inner.y
}

func (u *MyUnionUnion) Get_y() (func(*int, **string) *bool, bool) {
	if u._variant == _myUnionVariant_y {
		return u._inner.y, true
	}
	var zero func(*int, **string) *bool
	return zero, false
}

func NewMyUnionUnion_y(val func(*int, **string) *bool) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{y: val},
		_variant: _myUnionVariant_y,
	}
}

func (u *MyUnionUnion) Is_z() bool {
	return u._variant == _myUnionVariant_z
}

func (u *MyUnionUnion) Unwrap_z() any {
	if u._variant != _myUnionVariant_z {
		panic("called Unwrap_z on wrong variant")
	}
	return u._inner.z
}

func (u *MyUnionUnion) Get_z() (any, bool) {
	if u._variant == _myUnionVariant_z {
		return u._inner.z, true
	}
	var zero any
	return zero, false
}

func NewMyUnionUnion_z(val any) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{z: val},
		_variant: _myUnionVariant_z,
	}
}

func (u *MyUnionUnion) Is_aa() bool {
	return u._variant == _myUnionVariant_aa
}

func (u *MyUnionUnion) Unwrap_aa() []any {
	if u._variant != _myUnionVariant_aa {
		panic("called Unwrap_aa on wrong variant")
	}
	return u._inner.aa
}

func (u *MyUnionUnion) Get_aa() ([]any, bool) {
	if u._variant == _myUnionVariant_aa {
		return u._inner.aa, true
	}
	var zero []any
	return zero, false
}

func NewMyUnionUnion_aa(val []any) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{aa: val},
		_variant: _myUnionVariant_aa,
	}
}

func (u *MyUnionUnion) Is_bb() bool {
	return u._variant == _myUnionVariant_bb
}

func (u *MyUnionUnion) Unwrap_bb() map[any]any {
	if u._variant != _myUnionVariant_bb {
		panic("called Unwrap_bb on wrong variant")
	}
	return u._inner.bb
}

func (u *MyUnionUnion) Get_bb() (map[any]any, bool) {
	if u._variant == _myUnionVariant_bb {
		return u._inner.bb, true
	}
	var zero map[any]any
	return zero, false
}

func NewMyUnionUnion_bb(val map[any]any) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{bb: val},
		_variant: _myUnionVariant_bb,
	}
}

func (u *MyUnionUnion) Is_cc() bool {
	return u._variant == _myUnionVariant_cc
}

func (u *MyUnionUnion) Unwrap_cc() func() (int, int, error, error) {
	if u._variant != _myUnionVariant_cc {
		panic("called Unwrap_cc on wrong variant")
	}
	return u._inner.cc
}

func (u *MyUnionUnion) Get_cc() (func() (int, int, error, error), bool) {
	if u._variant == _myUnionVariant_cc {
		return u._inner.cc, true
	}
	var zero func() (int, int, error, error)
	return zero, false
}

func NewMyUnionUnion_cc(val func() (int, int, error, error)) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{cc: val},
		_variant: _myUnionVariant_cc,
	}
}

func (u *MyUnionUnion) Is_dd() bool {
	return u._variant == _myUnionVariant_dd
}

func (u *MyUnionUnion) Unwrap_dd() func(...string) {
	if u._variant != _myUnionVariant_dd {
		panic("called Unwrap_dd on wrong variant")
	}
	return u._inner.dd
}

func (u *MyUnionUnion) Get_dd() (func(...string), bool) {
	if u._variant == _myUnionVariant_dd {
		return u._inner.dd, true
	}
	var zero func(...string)
	return zero, false
}

func NewMyUnionUnion_dd(val func(...string)) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{dd: val},
		_variant: _myUnionVariant_dd,
	}
}

func (u *MyUnionUnion) Is_ee() bool {
	return u._variant == _myUnionVariant_ee
}

func (u *MyUnionUnion) Unwrap_ee() func(func(func(int) int) func(int) int) func(func(int) int) func(int) int {
	if u._variant != _myUnionVariant_ee {
		panic("called Unwrap_ee on wrong variant")
	}
	return u._inner.ee
}

func (u *MyUnionUnion) Get_ee() (func(func(func(int) int) func(int) int) func(func(int) int) func(int) int, bool) {
	if u._variant == _myUnionVariant_ee {
		return u._inner.ee, true
	}
	var zero func(func(func(int) int) func(int) int) func(func(int) int) func(int) int
	return zero, false
}

func NewMyUnionUnion_ee(val func(func(func(int) int) func(int) int) func(func(int) int) func(int) int) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{ee: val},
		_variant: _myUnionVariant_ee,
	}
}

func (u *MyUnionUnion) Is_ff() bool {
	return u._variant == _myUnionVariant_ff
}

func (u *MyUnionUnion) Unwrap_ff() rune {
	if u._variant != _myUnionVariant_ff {
		panic("called Unwrap_ff on wrong variant")
	}
	return u._inner.ff
}

func (u *MyUnionUnion) Get_ff() (rune, bool) {
	if u._variant == _myUnionVariant_ff {
		return u._inner.ff, true
	}
	var zero rune
	return zero, false
}

func NewMyUnionUnion_ff(val rune) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{ff: val},
		_variant: _myUnionVariant_ff,
	}
}

func (u *MyUnionUnion) Is_gg() bool {
	return u._variant == _myUnionVariant_gg
}

func (u *MyUnionUnion) Unwrap_gg() int32 {
	if u._variant != _myUnionVariant_gg {
		panic("called Unwrap_gg on wrong variant")
	}
	return u._inner.gg
}

func (u *MyUnionUnion) Get_gg() (int32, bool) {
	if u._variant == _myUnionVariant_gg {
		return u._inner.gg, true
	}
	var zero int32
	return zero, false
}

func NewMyUnionUnion_gg(val int32) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{gg: val},
		_variant: _myUnionVariant_gg,
	}
}

func (u *MyUnionUnion) Is_hh() bool {
	return u._variant == _myUnionVariant_hh
}

func (u *MyUnionUnion) Unwrap_hh() byte {
	if u._variant != _myUnionVariant_hh {
		panic("called Unwrap_hh on wrong variant")
	}
	return u._inner.hh
}

func (u *MyUnionUnion) Get_hh() (byte, bool) {
	if u._variant == _myUnionVariant_hh {
		return u._inner.hh, true
	}
	var zero byte
	return zero, false
}

func NewMyUnionUnion_hh(val byte) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{hh: val},
		_variant: _myUnionVariant_hh,
	}
}

func (u *MyUnionUnion) Is_ii() bool {
	return u._variant == _myUnionVariant_ii
}

func (u *MyUnionUnion) Unwrap_ii() uint8 {
	if u._variant != _myUnionVariant_ii {
		panic("called Unwrap_ii on wrong variant")
	}
	return u._inner.ii
}

func (u *MyUnionUnion) Get_ii() (uint8, bool) {
	if u._variant == _myUnionVariant_ii {
		return u._inner.ii, true
	}
	var zero uint8
	return zero, false
}

func NewMyUnionUnion_ii(val uint8) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{ii: val},
		_variant: _myUnionVariant_ii,
	}
}

func (u *MyUnionUnion) Is_jj() bool {
	return u._variant == _myUnionVariant_jj
}

func (u *MyUnionUnion) Unwrap_jj() Generic[int] {
	if u._variant != _myUnionVariant_jj {
		panic("called Unwrap_jj on wrong variant")
	}
	return u._inner.jj
}

func (u *MyUnionUnion) Get_jj() (Generic[int], bool) {
	if u._variant == _myUnionVariant_jj {
		return u._inner.jj, true
	}
	var zero Generic[int]
	return zero, false
}

func NewMyUnionUnion_jj(val Generic[int]) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{jj: val},
		_variant: _myUnionVariant_jj,
	}
}

func (u *MyUnionUnion) Is_kk() bool {
	return u._variant == _myUnionVariant_kk
}

func (u *MyUnionUnion) Unwrap_kk() Generic[string] {
	if u._variant != _myUnionVariant_kk {
		panic("called Unwrap_kk on wrong variant")
	}
	return u._inner.kk
}

func (u *MyUnionUnion) Get_kk() (Generic[string], bool) {
	if u._variant == _myUnionVariant_kk {
		return u._inner.kk, true
	}
	var zero Generic[string]
	return zero, false
}

func NewMyUnionUnion_kk(val Generic[string]) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{kk: val},
		_variant: _myUnionVariant_kk,
	}
}

func (u *MyUnionUnion) Is_ll() bool {
	return u._variant == _myUnionVariant_ll
}

func (u *MyUnionUnion) Unwrap_ll() Generic[*float64] {
	if u._variant != _myUnionVariant_ll {
		panic("called Unwrap_ll on wrong variant")
	}
	return u._inner.ll
}

func (u *MyUnionUnion) Get_ll() (Generic[*float64], bool) {
	if u._variant == _myUnionVariant_ll {
		return u._inner.ll, true
	}
	var zero Generic[*float64]
	return zero, false
}

func NewMyUnionUnion_ll(val Generic[*float64]) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{ll: val},
		_variant: _myUnionVariant_ll,
	}
}

func (u *MyUnionUnion) Is_mm() bool {
	return u._variant == _myUnionVariant_mm
}

func (u *MyUnionUnion) Unwrap_mm() TwoParam[int, string] {
	if u._variant != _myUnionVariant_mm {
		panic("called Unwrap_mm on wrong variant")
	}
	return u._inner.mm
}

func (u *MyUnionUnion) Get_mm() (TwoParam[int, string], bool) {
	if u._variant == _myUnionVariant_mm {
		return u._inner.mm, true
	}
	var zero TwoParam[int, string]
	return zero, false
}

func NewMyUnionUnion_mm(val TwoParam[int, string]) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{mm: val},
		_variant: _myUnionVariant_mm,
	}
}

func (u *MyUnionUnion) Is_nn() bool {
	return u._variant == _myUnionVariant_nn
}

func (u *MyUnionUnion) Unwrap_nn() Generic[Generic[int]] {
	if u._variant != _myUnionVariant_nn {
		panic("called Unwrap_nn on wrong variant")
	}
	return u._inner.nn
}

func (u *MyUnionUnion) Get_nn() (Generic[Generic[int]], bool) {
	if u._variant == _myUnionVariant_nn {
		return u._inner.nn, true
	}
	var zero Generic[Generic[int]]
	return zero, false
}

func NewMyUnionUnion_nn(val Generic[Generic[int]]) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{nn: val},
		_variant: _myUnionVariant_nn,
	}
}

func (u *MyUnionUnion) Is_oo() bool {
	return u._variant == _myUnionVariant_oo
}

func (u *MyUnionUnion) Unwrap_oo() time.Time {
	if u._variant != _myUnionVariant_oo {
		panic("called Unwrap_oo on wrong variant")
	}
	return u._inner.oo
}

func (u *MyUnionUnion) Get_oo() (time.Time, bool) {
	if u._variant == _myUnionVariant_oo {
		return u._inner.oo, true
	}
	var zero time.Time
	return zero, false
}

func NewMyUnionUnion_oo(val time.Time) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{oo: val},
		_variant: _myUnionVariant_oo,
	}
}

func (u *MyUnionUnion) Is_pp() bool {
	return u._variant == _myUnionVariant_pp
}

func (u *MyUnionUnion) Unwrap_pp() time.Duration {
	if u._variant != _myUnionVariant_pp {
		panic("called Unwrap_pp on wrong variant")
	}
	return u._inner.pp
}

func (u *MyUnionUnion) Get_pp() (time.Duration, bool) {
	if u._variant == _myUnionVariant_pp {
		return u._inner.pp, true
	}
	var zero time.Duration
	return zero, false
}

func NewMyUnionUnion_pp(val time.Duration) MyUnionUnion {
	return MyUnionUnion{
		_inner:   myUnion{pp: val},
		_variant: _myUnionVariant_pp,
	}
}

func Match_MyUnionUnion[_R any](u *MyUnionUnion, on_a func(int) _R, on_b func(string) _R, on_c func(*float64) _R, on_d func([]*int) _R, on_e func([5]byte) _R, on_f func(map[string][]int) _R, on_g func(map[int]map[string]bool) _R, on_h func(chan int) _R, on_i func(<-chan string) _R, on_j func(chan<- bool) _R, on_k func(func()) _R, on_l func(func(a int, b string) (int, error)) _R, on_m func(func(format string, args ...any) string) _R, on_n func(func(x int, y int) (sum int, diff int)) _R, on_o func(func(multiplier int) func(int) int) _R, on_p func(func(callback func(int) bool) error) _R, on_q func(func(in <-chan int, out chan<- int)) _R, on_r func(func(ctx context.Context) error) _R, on_s func(func(w io.Writer, r io.Reader) (int64, error)) _R, on_t func(*func(int) int) _R, on_u func([]func() error) _R, on_v func(map[string]func(int) int) _R, on_w func(***int) _R, on_x func(*[]*[3]int) _R, on_y func(func(*int, **string) *bool) _R, on_z func(any) _R, on_aa func([]any) _R, on_bb func(map[any]any) _R, on_cc func(func() (int, int, error, error)) _R, on_dd func(func(...string)) _R, on_ee func(func(func(func(int) int) func(int) int) func(func(int) int) func(int) int) _R, on_ff func(rune) _R, on_gg func(int32) _R, on_hh func(byte) _R, on_ii func(uint8) _R, on_jj func(Generic[int]) _R, on_kk func(Generic[string]) _R, on_ll func(Generic[*float64]) _R, on_mm func(TwoParam[int, string]) _R, on_nn func(Generic[Generic[int]]) _R, on_oo func(time.Time) _R, on_pp func(time.Duration) _R, on_Invalid func() _R) _R {
	switch u._variant {
	case _myUnionVariant_a:
		return on_a(u._inner.a)
	case _myUnionVariant_b:
		return on_b(u._inner.b)
	case _myUnionVariant_c:
		return on_c(u._inner.c)
	case _myUnionVariant_d:
		return on_d(u._inner.d)
	case _myUnionVariant_e:
		return on_e(u._inner.e)
	case _myUnionVariant_f:
		return on_f(u._inner.f)
	case _myUnionVariant_g:
		return on_g(u._inner.g)
	case _myUnionVariant_h:
		return on_h(u._inner.h)
	case _myUnionVariant_i:
		return on_i(u._inner.i)
	case _myUnionVariant_j:
		return on_j(u._inner.j)
	case _myUnionVariant_k:
		return on_k(u._inner.k)
	case _myUnionVariant_l:
		return on_l(u._inner.l)
	case _myUnionVariant_m:
		return on_m(u._inner.m)
	case _myUnionVariant_n:
		return on_n(u._inner.n)
	case _myUnionVariant_o:
		return on_o(u._inner.o)
	case _myUnionVariant_p:
		return on_p(u._inner.p)
	case _myUnionVariant_q:
		return on_q(u._inner.q)
	case _myUnionVariant_r:
		return on_r(u._inner.r)
	case _myUnionVariant_s:
		return on_s(u._inner.s)
	case _myUnionVariant_t:
		return on_t(u._inner.t)
	case _myUnionVariant_u:
		return on_u(u._inner.u)
	case _myUnionVariant_v:
		return on_v(u._inner.v)
	case _myUnionVariant_w:
		return on_w(u._inner.w)
	case _myUnionVariant_x:
		return on_x(u._inner.x)
	case _myUnionVariant_y:
		return on_y(u._inner.y)
	case _myUnionVariant_z:
		return on_z(u._inner.z)
	case _myUnionVariant_aa:
		return on_aa(u._inner.aa)
	case _myUnionVariant_bb:
		return on_bb(u._inner.bb)
	case _myUnionVariant_cc:
		return on_cc(u._inner.cc)
	case _myUnionVariant_dd:
		return on_dd(u._inner.dd)
	case _myUnionVariant_ee:
		return on_ee(u._inner.ee)
	case _myUnionVariant_ff:
		return on_ff(u._inner.ff)
	case _myUnionVariant_gg:
		return on_gg(u._inner.gg)
	case _myUnionVariant_hh:
		return on_hh(u._inner.hh)
	case _myUnionVariant_ii:
		return on_ii(u._inner.ii)
	case _myUnionVariant_jj:
		return on_jj(u._inner.jj)
	case _myUnionVariant_kk:
		return on_kk(u._inner.kk)
	case _myUnionVariant_ll:
		return on_ll(u._inner.ll)
	case _myUnionVariant_mm:
		return on_mm(u._inner.mm)
	case _myUnionVariant_nn:
		return on_nn(u._inner.nn)
	case _myUnionVariant_oo:
		return on_oo(u._inner.oo)
	case _myUnionVariant_pp:
		return on_pp(u._inner.pp)
	case _myUnionVariant_Invalid:
		return on_Invalid()
	default:
		panic("unreachable")
	}
}
