// Code generated by gunion. DO NOT EDIT.

package aliasedimport

import (
	"context"
	"io"
)

type _myUnionVariant int

const (
	_myUnionVariant__invalid _myUnionVariant = 0
	_myUnionVariant_a        _myUnionVariant = 1
	_myUnionVariant_b        _myUnionVariant = 2
	_myUnionVariant_c        _myUnionVariant = 3
)

type MyUnionUnion struct {
	variant _myUnionVariant
	inner   myUnion
}

func (u *MyUnionUnion) Is_Invalid() bool {
	return u.variant == _myUnionVariant__invalid
}

func NewMyUnionUnion_Invalid() MyUnionUnion {
	return MyUnionUnion{variant: _myUnionVariant__invalid}
}

func (u *MyUnionUnion) Is_a() bool {
	return u.variant == _myUnionVariant_a
}

func (u *MyUnionUnion) Unwrap_a() context.Context {
	if u.variant != _myUnionVariant_a {
		panic("called Unwrap_a on wrong variant")
	}
	return u.inner.a
}

func (u *MyUnionUnion) Get_a() (context.Context, bool) {
	if u.variant == _myUnionVariant_a {
		return u.inner.a, true
	}
	var zero context.Context
	return zero, false
}

func NewMyUnionUnion_a(val context.Context) MyUnionUnion {
	return MyUnionUnion{
		inner:   myUnion{a: val},
		variant: _myUnionVariant_a,
	}
}

func (u *MyUnionUnion) Is_b() bool {
	return u.variant == _myUnionVariant_b
}

func (u *MyUnionUnion) Unwrap_b() io.Writer {
	if u.variant != _myUnionVariant_b {
		panic("called Unwrap_b on wrong variant")
	}
	return u.inner.b
}

func (u *MyUnionUnion) Get_b() (io.Writer, bool) {
	if u.variant == _myUnionVariant_b {
		return u.inner.b, true
	}
	var zero io.Writer
	return zero, false
}

func NewMyUnionUnion_b(val io.Writer) MyUnionUnion {
	return MyUnionUnion{
		inner:   myUnion{b: val},
		variant: _myUnionVariant_b,
	}
}

func (u *MyUnionUnion) Is_c() bool {
	return u.variant == _myUnionVariant_c
}

func (u *MyUnionUnion) Unwrap_c() io.Reader {
	if u.variant != _myUnionVariant_c {
		panic("called Unwrap_c on wrong variant")
	}
	return u.inner.c
}

func (u *MyUnionUnion) Get_c() (io.Reader, bool) {
	if u.variant == _myUnionVariant_c {
		return u.inner.c, true
	}
	var zero io.Reader
	return zero, false
}

func NewMyUnionUnion_c(val io.Reader) MyUnionUnion {
	return MyUnionUnion{
		inner:   myUnion{c: val},
		variant: _myUnionVariant_c,
	}
}

func Match[_R any](u *MyUnionUnion, on_a func(context.Context) _R, on_b func(io.Writer) _R, on_c func(io.Reader) _R, on_Invalid func() _R) _R {
	switch u.variant {
	case _myUnionVariant_a:
		return on_a(u.inner.a)
	case _myUnionVariant_b:
		return on_b(u.inner.b)
	case _myUnionVariant_c:
		return on_c(u.inner.c)
	case _myUnionVariant__invalid:
		return on_Invalid()
	default:
		panic("unreachable")
	}
}
